name: "release"

on: workflow_dispatch
# on:
#   repository_dispatch:
#     types: [on-demand-release]

env:
  GECKO_ID: tabalanche-extension@huaidan.org
  UPDATE_URL: https://raw.githubusercontent.com/sunlei/tabalanche-extension-releases/master/updates.json

jobs:
  publish-tabalanche:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository `self`
        uses: actions/checkout@v4

      - name: Checkout repository `tabalanche-extension``
        uses: actions/checkout@v4
        with:
          repository: eight04/tabalanche-extension
          ref: dev-dup
          path: src

      - name: ls
        run: |
          ls -alh .

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          # cache: "pnpm" # npm / yarn / pnpm

      - name: Install web-ext
        run: |
          pnpm install --global web-ext

      - name: Install jq if not already installed
        run: |
          if ! command -v jq &> /dev/null; then
            sudo apt update && sudo apt install -y jq
          fi

      - name: Set version
        run: |
          CALVER_VERSION=$(date +'%Y.%m.%d.%H%M')
          echo "CALVER_VERSION=${CALVER_VERSION}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=tabalanche-${CALVER_VERSION}.xpi" >> $GITHUB_ENV

      - name: Update manifest.json with version
        run: |
          bash scripts/update-manifest.sh

      # - name: Build extension
      #   run: |
      #     web-ext build --source-dir src --filename ${{ env.ARTIFACT_NAME }}
      #     ls -alh .
      #     ls -alh web-ext-artifacts

      # - name: Build and sign extension
      #   run: |
      #     web-ext sign \
      #       --source-dir src \
      #       --channel unlisted \
      #       --api-key ${{ secrets.AMO_JWT_ISSUER }} \
      #       --api-secret ${{ secrets.AMO_JWT_SECRET }}
      #     ls -alh .
      #     ls -alh web-ext-artifacts
