name: "release"

on: workflow_dispatch
# on:
#   repository_dispatch:
#     types: [on-demand-release]

jobs:
  publish-tabalanche:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v4
        with:
          repository: eight04/tabalanche-extension
          ref: dev-dup
          path: src

      - name: ls
        run: |
          ls -alh .

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          # cache: "pnpm" # npm / yarn / pnpm

      - name: Install web-ext
        run: |
          pnpm install --global web-ext

      - name: Set CalVer version
        run: |
          echo "CALVER_VERSION=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=tabalanche-${CALVER_VERSION}.xpi" >> $GITHUB_ENV

      - name: Build extension
        run: |
          web-ext build --source-dir src --filename ${{ env.ARTIFACT_NAME }}
          ls -alh .
          ls -alh web-ext-artifacts

      # - name: Build and sign extension
      #   run: |
      #     web-ext sign \
      #       --api-key ${{ secrets.AMO_JWT_ISSUER }} \
      #       --api-secret ${{ secrets.AMO_JWT_SECRET }}
