name: "release"

on: workflow_dispatch
# on:
#   repository_dispatch:
#     types: [on-demand-release]

env:
  GECKO_ID: tabalanche-extension@huaidan.org
  UPDATE_URL: https://raw.githubusercontent.com/sunlei/tabalanche-extension-releases/master/updates.json
  WEB_EXT_ARTIFACTS_DIR: web-ext-artifacts

jobs:
  publish-tabalanche:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository `self`
        uses: actions/checkout@v4

      - name: Checkout repository `tabalanche-extension``
        uses: actions/checkout@v4
        with:
          repository: eight04/tabalanche-extension
          ref: dev-dup
          path: src

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          # cache: "pnpm" # npm / yarn / pnpm

      - name: Install web-ext
        run: |
          pnpm install --global web-ext

      - name: Install jq if not already installed
        run: |
          if ! command -v jq &> /dev/null; then
            sudo apt update && sudo apt install -y jq
          fi

      - name: Set version
        run: |
          CALVER_VERSION=$(date +'%Y.%-m.%-d.%H%M')
          echo "CALVER_VERSION=${CALVER_VERSION}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=tabalanche-${CALVER_VERSION}.xpi" >> $GITHUB_ENV

      - name: Update manifest.json
        run: |
          bash scripts/update-manifest.sh

      # - name: Build extension
      #   run: |
      #     web-ext build --source-dir src --filename ${{ env.ARTIFACT_NAME }}
      #     ls -alh .
      #     ls -alh ${{ env.WEB_EXT_ARTIFACTS_DIR }}

      - name: Build and sign extension
        run: |
          web-ext sign \
            --source-dir src \
            --channel unlisted \
            --api-key ${{ secrets.AMO_JWT_ISSUER }} \
            --api-secret ${{ secrets.AMO_JWT_SECRET }}
          ls -alh ${{ env.WEB_EXT_ARTIFACTS_DIR }}

      - name: Rename signed extension
        run: |
          bash scripts/rename-xpi.sh
          ls -alh "$WEB_EXT_ARTIFACTS_DIR"

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.GECKO_ID }}
      #     path: ${{ env.WEB_EXT_ARTIFACTS_DIR }}/${{ env.ARTIFACT_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.WEB_EXT_ARTIFACTS_DIR }}/${{ env.ARTIFACT_NAME }}
          tag_name: v${{ env.CALVER_VERSION }}
          name: v${{ env.CALVER_VERSION }}

      - name: Update updates.json
        run: |
          bash scripts/update-updates.sh

      - name: Git commit updates.json
        run: |
          git config --local user.name "GitHub Action 🤖"
          git config --local user.email "actions@github.com"

          rm -rf src
          git add ./updates.json
          git commit -m "feat: release v${{ env.CALVER_VERSION }}"
          git push
